# Assignment: Processed E-commerce Dataset (Day 9)

Create a Processed E-commerce Dataset using the three provided CSV files: Orders, Customers, and Products in the "Study Material" tab in the LMS. Load the datasets using Pandas and combine the related information using merge(), while using concat() to demonstrate combining DataFrames. Use apply() to create or transform useful columns, and use DateTime operations to convert the order date and extract information such as the month, day, or day of the week. Organize the resulting information into a clean, meaningful DataFrame and export the final processed dataset as a CSV file. Upload the notebook, the input datasets and the final processed dataset on a GitHub repository before submitting your work.

In [ ]:
import pandas as pd

In [27]:
orders = pd.read_csv("Day9_Orders.csv")
orders.head()

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered

In [28]:
customers = pd.read_csv("Day9_Customers.csv")
#customers.info()
customers.head()

  Customer_ID Customer_Name      City Region Membership_Type
0        C001  Aarav Sharma  Srinagar  North         Premium
1        C002     Zoya Khan     Delhi  North         Regular
2        C003   Rohan Mehta    Mumbai   West         Premium
3        C004  Ananya Singh     Jammu  North         Regular
4        C005     Kabir Ali   Lucknow  North             New

In [29]:
products = pd.read_csv("Day9_Products.csv")
#products.info()
products.head()

  Product_ID         Product_Name     Category  Unit_Price     Brand
0       P001  Wireless Headphones  Electronics        1499  SoundMax
1       P002  Mechanical Keyboard  Electronics        2499    KeyPro
2       P003       Wireless Mouse  Electronics         899  TechGear
3       P004          Smart Watch  Electronics        3299   FitTech
4       P005           Power Bank  Electronics        1199  VoltPlus

In [30]:
orders_batch1 = orders[['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']].head(5)
orders_batch2 = orders[['Order_ID', 'Order_Date', 'Customer_ID', 'Product_ID', 'Quantity', 'Payment_Method', 'Order_Status']].tail(5)

concat_demo = pd.concat([orders_batch1, orders_batch2], ignore_index=True)
concat_demo

,Order_ID,Order_Date,Customer_ID,Product_ID,Quantity,Payment_Method,Order_Status
0,O0001,2026-02-19,C027,P019,2,Credit Card,Delivered
1,O0002,2026-01-25,C006,P003,2,Debit Card,Delivered
2,O0003,2026-02-26,C015,P004,1,Cash on Delivery,Delivered
3,O0004,2026-03-04,C024,P015,3,Net Banking,Delivered
4,O0005,2026-03-29,C025,P009,5,Credit Card,Delivered
5,O0116,2026-02-19,C025,P010,1,Net Banking,Delivered
6,O0117,2026-02-21,C019,P015,3,Cash on Delivery,Shipped
7,O0118,2026-03-09,C025,P016,4,Credit Card,Delivered
8,O0119,2026-02-03,C015,P019,2,Debit Card,Delivered
9,O0120,2026-01-21,C013,P020,1,Cash on Delivery,Cancelled

In [ ]:

ecommerce_df = orders.merge(customers, on='Customer_ID', how='left') # same column = customer_id in both datasets
ecommerce_df = ecommerce_df.merge(products, on='Product_ID', how='left')#same column = product_id in both datasets

ecommerce_df['Order_Type'] = ecommerce_df['Quantity'].apply(lambda x: 'Bulk' if x >= 3 else 'Single/Small')
ecommerce_df['Total_Price'] = ecommerce_df.apply(lambda row: row['Quantity'] * row['Unit_Price'], axis=1)


ecommerce_df[['Order_ID', 'Customer_Name', 'Membership_Type', 'Order_Type', 'Total_Price']].head()

  Order_ID  Customer_Name Membership_Type    Order_Type  Total_Price
0    O0001  Harsh Vardhan         Premium  Single/Small         4998
1    O0002   Ishita Gupta         Premium  Single/Small         1798
2    O0003    Karan Joshi         Regular  Single/Small         3299
3    O0004    Maryam Khan         Regular          Bulk         2997
4    O0005   Reyansh Jain             New          Bulk        17495

In [25]:
ecommerce_df['Order_Date'] = pd.to_datetime(ecommerce_df['Order_Date'])

ecommerce_df['Month'] = ecommerce_df['Order_Date'].dt.month
ecommerce_df['Month_Name'] = ecommerce_df['Order_Date'].dt.month_name()
ecommerce_df['Day'] = ecommerce_df['Order_Date'].dt.day
ecommerce_df['Day_of_Week'] = ecommerce_df['Order_Date'].dt.day_name()

ecommerce_df[['Order_ID', 'Order_Date', 'Month_Name', 'Day', 'Day_of_Week']].head()

  Order_ID Order_Date Month_Name  Day Day_of_Week
0    O0001 2026-02-19   February   19    Thursday
1    O0002 2026-01-25    January   25      Sunday
2    O0003 2026-02-26   February   26    Thursday
3    O0004 2026-03-04      March    4   Wednesday
4    O0005 2026-03-29      March   29      Sunday

In [26]:
ecommerce_df.to_csv('Ecommerce_Dataset.csv', index=False)
print("Ecommerce dataset has been saved to 'Ecommerce_Dataset.csv' successfully.")

Ecommerce dataset has been saved to 'Ecommerce_Dataset.csv' successfully.