Assignment: Cleaned Company Employee Dataset (Day 11)
Create a Cleaned Company Employee Dataset using the provided messy company dataset. Load and inspect the dataset using Pandas, identify and quantify missing values, inconsistent entries, incorrect data types, and duplicate records, and apply appropriate data-cleaning techniques to resolve these issues. Use suitable methods such as isnull(), dropna(), fillna(), mean/median/mode imputation, forward filling, and drop_duplicates() where appropriate, while making sensible decisions about which method should be used for each problem. Verify the dataset after cleaning, compare its condition before and after the cleaning process, and export the final cleaned dataset as a CSV file along with a brief summary of the cleaning steps performed.

In [94]:
import pandas as pd

In [95]:
data = pd.read_csv("Day11_Messy_Company_Employee_Dataset.csv")
data.head(10)

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,NaN,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid
5,EMP0117,Zoya Kapoor,Finance,Finance Manager,42.0,Male,128567.0,15.4,2017-08-02,Chennai,4.0,Hybrid
6,EMP0081,Maryam Mir,Marketing,Content Strategist,37.0,Male,58878.0,1.8,2024-01-18,Pune,2.0,Office
7,EMP0026,Omar Das,Engineering,QA Engineer,38.0,Male,112276.0,12.0,2019-05-14,Chandigarh,4.0,Hybrid
8,EMP0129,Dev Ahmed,Data & Analytics,Data Scientist,45.0,Male,135730.0,14.1,2021-01-27,Srinagar,2.0,Remote
9,EMP0121,Karan Patel,Data & Analytics,BI Analyst,40.0,Female,101886.0,8.5,2020-06-28,Chennai,4.0,Remote

In [96]:
null_values = data.isnull().sum()
null_values

Employee_ID          0
Employee_Name        0
Department           5
Job_Title            0
Age                  4
Gender               5
Annual_Salary        5
Experience_Years     3
Joining_Date         0
City                 5
Performance_Score    3
Work_Mode            2
dtype: int64

In [97]:
before_cleaning= data.isnull().sum().sum()
print("Missing values before cleaning:",before_cleaning)

before_duplicates_cleaned = data.duplicated().sum()
print("Duplicates before cleaning:",before_duplicates_cleaned)
print(data.duplicated().sum())

before_raws_cleaned = data.shape[0]
print("before shape of raw:",before_raws_cleaned)

print(data.dtypes)

Missing values before cleaning: 32
Duplicates before cleaning: 7
7
before shape of raw: 157
Employee_ID           object
Employee_Name         object
Department            object
Job_Title             object
Age                  float64
Gender                object
Annual_Salary        float64
Experience_Years     float64
Joining_Date          object
City                  object
Performance_Score    float64
Work_Mode             object
dtype: object

In [98]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 157 entries, 0 to 156
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Employee_ID        157 non-null    object
 1   Employee_Name      157 non-null    object
 2   Department         152 non-null    object
 3   Job_Title          157 non-null    object
 4   Age                153 non-null    float64
 5   Gender             152 non-null    object
 6   Annual_Salary      152 non-null    float64
 7   Experience_Years   154 non-null    float64
 8   Joining_Date       157 non-null    object
 9   City               152 non-null    object
 10  Performance_Score  154 non-null    float64
 11  Work_Mode          155 non-null    object
dtypes: float64(4), object(8)
memory usage: 14.8+ KB

In [101]:
data.describe(include='all')

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
count,157,157,152,157,153.000000,152,152.000000,154.000000,157,152,154.000000,155
unique,150,130,10,23,NaN,5,NaN,NaN,147,13,NaN,5
top,EMP0075,Nikhil Das,Marketing,Data Scientist,NaN,Male,NaN,NaN,2025-08-17,Chandigarh,NaN,Remote
freq,2,3,23,13,NaN,75,NaN,NaN,2,24,NaN,56
mean,NaN,NaN,NaN,NaN,38.130719,NaN,89240.592105,8.990909,NaN,NaN,3.525974,NaN
std,NaN,NaN,NaN,NaN,9.361661,NaN,22626.172309,4.983874,NaN,NaN,0.930233,NaN
min,NaN,NaN,NaN,NaN,21.000000,NaN,43331.000000,0.600000,NaN,NaN,2.000000,NaN
25%,NaN,NaN,NaN,NaN,30.000000,NaN,71198.500000,4.450000,NaN,NaN,3.000000,NaN
50%,NaN,NaN,NaN,NaN,39.000000,NaN,90046.500000,9.350000,NaN,NaN,4.000000,NaN
75%,NaN,NaN,NaN,NaN,46.000000,NaN,107328.000000,13.200000,NaN,NaN,4.000000,NaN
max,NaN,NaN,NaN,NaN,52.000000,NaN,162942.000000,17.400000,NaN,NaN,5.000000,NaN

In [104]:
data["Department"] = data["Department"].str.strip().str.title()
data["Department"] = data["Department"].fillna(data["Department"].mode()[0])
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [105]:

data["Age"] = data["Age"].fillna(data["Age"].median())
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [106]:
data["Gender"] = data["Gender"].str.strip().str.title()
data["Gender"] = data["Gender"].fillna(data["Gender"].mode()[0])
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [107]:

data["Annual_Salary"] = data["Annual_Salary"].fillna(data["Annual_Salary"].median())
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.2,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.1,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.2,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,NaN,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.9,2018-07-24,Hyderabad,4.0,Hybrid

In [108]:

data["Experience_Years"] = data["Experience_Years"].fillna(data["Experience_Years"].median())
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid

In [109]:

data["Performance_Score"] = data["Performance_Score"].fillna(data["Performance_Score"].median())
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid

In [110]:
data["City"] = data["City"].str.strip().str.title()
data["City"] = data["City"].ffill().bfill()
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid

In [111]:
data["Work_Mode"] = data["Work_Mode"].str.strip().str.title()
data["Work_Mode"] = data["Work_Mode"].ffill()
data.head()

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid

In [112]:
data = data.drop_duplicates()
data

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
...,...,...,...,...,...,...,...,...,...,...,...,...
151,EMP0050,Alina Patel,Finance,Financial Analyst,22.0,Male,74903.0,7.60,2020-01-18,Pune,2.0,Remote
152,EMP0132,Manya Rao,Marketing,Content Strategist,30.0,Female,49522.0,0.60,2021-11-25,Delhi,2.0,Remote
153,EMP0073,Karan Kapoor,Customer Success,Customer Success Manager,42.0,Male,43331.0,1.10,2018-03-23,Jaipur,3.0,Hybrid
154,EMP0124,Saira Kapoor,Engineering,QA Engineer,33.0,Male,94812.0,7.20,2024-06-12,Jaipur,4.0,Hybrid
155,EMP0020,Sara Ali,Sales,Sales Executive,22.0,Female,51745.0,2.40,2020-11-19,Jaipur,2.0,Office

In [113]:
data["Joining_Date"] = pd.to_datetime(data["Joining_Date"])
data

,Employee_ID,Employee_Name,Department,Job_Title,Age,Gender,Annual_Salary,Experience_Years,Joining_Date,City,Performance_Score,Work_Mode
0,EMP0098,Ananya Nair,Engineering,Data Scientist,48.0,Other,108371.0,13.20,2017-06-13,Pune,5.0,Office
1,EMP0046,Faizan Khan,Marketing,Marketing Manager,31.0,Female,108824.0,12.10,2021-09-15,Mumbai,2.0,Office
2,EMP0017,Saira Malik,Human Resources,HR Manager,28.0,Female,119400.0,13.20,2021-02-05,Bengaluru,3.0,Remote
3,EMP0105,Neha Menon,Engineering,Software Engineer,30.0,Female,111847.0,9.35,2018-08-05,Jaipur,4.0,Hybrid
4,EMP0143,Hiba Menon,Sales,Sales Manager,25.0,Female,78677.0,10.90,2018-07-24,Hyderabad,4.0,Hybrid
...,...,...,...,...,...,...,...,...,...,...,...,...
151,EMP0050,Alina Patel,Finance,Financial Analyst,22.0,Male,74903.0,7.60,2020-01-18,Pune,2.0,Remote
152,EMP0132,Manya Rao,Marketing,Content Strategist,30.0,Female,49522.0,0.60,2021-11-25,Delhi,2.0,Remote
153,EMP0073,Karan Kapoor,Customer Success,Customer Success Manager,42.0,Male,43331.0,1.10,2018-03-23,Jaipur,3.0,Hybrid
154,EMP0124,Saira Kapoor,Engineering,QA Engineer,33.0,Male,94812.0,7.20,2024-06-12,Jaipur,4.0,Hybrid
155,EMP0020,Sara Ali,Sales,Sales Executive,22.0,Female,51745.0,2.40,2020-11-19,Jaipur,2.0,Office

In [114]:
data.nunique()

Employee_ID          150
Employee_Name        130
Department             8
Job_Title             23
Age                   32
Gender                 3
Annual_Salary        147
Experience_Years     106
Joining_Date         147
City                  10
Performance_Score      4
Work_Mode              3
dtype: int64

In [118]:
after_cleaning = data.isnull().sum().sum()
print("Missing values after cleaning:",after_cleaning)

after_duplicates_cleaned = data.duplicated().sum()
print("Duplicates after cleaning:",after_duplicates_cleaned)


after_raws_cleaned = data.shape[0]
print("Final shape of raw:",after_raws_cleaned)

print(data.dtypes)

Missing values after cleaning: 0
Duplicates after cleaning: 0
Final shape of raw: 150
Employee_ID                  object
Employee_Name                object
Department                   object
Job_Title                    object
Age                         float64
Gender                       object
Annual_Salary               float64
Experience_Years            float64
Joining_Date         datetime64[ns]
City                         object
Performance_Score           float64
Work_Mode                    object
dtype: object

In [119]:

# Comparison
print("BEFORE CLEANING")
print("Rows:", before_raws_cleaned)
print("Missing Values:", before_cleaning)
print("Duplicates:", before_duplicates_cleaned )


print("\nAFTER CLEANING")
print("Rows:", after_raws_cleaned)
print("Missing Values:", after_cleaning)
print("Duplicates:", after_duplicates_cleaned)

BEFORE CLEANING
Rows: 157
Missing Values: 32
Duplicates: 7

AFTER CLEANING
Rows: 150
Missing Values: 0
Duplicates: 0

In [120]:
data.to_csv("cleaned_Day_11.csv")
print("dataset is cleaned and stored in:cleaned_Day_11.csv" )

dataset is cleaned and stored in:cleaned_Day_11.csv